import { ParseThemeColors } from 'types/index.ts';

const integratedTerminalColorsProps = [
  'terminal.background',
  'terminal.border',
  'terminal.foreground',
  'terminal.ansiBlack',
  'terminal.ansiBlue',
  'terminal.ansiBrightBlack',
  'terminal.ansiBrightBlue',
  'terminal.ansiBrightCyan',
  'terminal.ansiBrightGreen',
  'terminal.ansiBrightMagenta',
  'terminal.ansiBrightRed',
  'terminal.ansiBrightWhite',
  'terminal.ansiBrightYellow',
  'terminal.ansiCyan',
  'terminal.ansiGreen',
  'terminal.ansiMagenta',
  'terminal.ansiRed',
  'terminal.ansiWhite',
  'terminal.ansiYellow',
  'terminal.selectionBackground',
  'terminal.selectionForeground',
  'terminal.inactiveSelectionBackground',
  'terminal.findMatchBackground',
  'terminal.findMatchBorder',
  'terminal.findMatchHighlightBackground',
  'terminal.findMatchHighlightBorder',
  'terminal.hoverHighlightBackground',
  'terminalCursor.background',
  'terminalCursor.foreground',
  'terminal.dropBackground',
  'terminal.tab.activeBorder',
  'terminalCommandDecoration.defaultBackground',
  'terminalCommandDecoration.successBackground',
  'terminalCommandDecoration.errorBackground',
  'terminalOverviewRuler.cursorForeground',
  'terminalOverviewRuler.findMatchForeground',
] as const;

export type IntegratedTerminalColors = ParseThemeColors<typeof integratedTerminalColorsProps>;
