import { colors, aliases } from '@synxty/design-tokens';
import { TESTING } from 'constants/index.ts';
import { General } from 'types/index.ts';

const { primary, info, danger, warning } = aliases;
const { black, white } = colors;

export const general: General = {
  'editor.background': black.tint[20],
  'editor.foreground': white.shade[10],
  'editorLineNumber.foreground': black.tint[90],
  'editorLineNumber.activeForeground': primary.DEFAULT,
  'editorLineNumber.dimmedForeground': black.tint[50],
  'editorCursor.background': black.tint[10],
  'editorCursor.foreground': primary.DEFAULT,
  'editor.selectionBackground': `${black.tint[120]}40`,
  'editor.selectionForeground': black.tint[10],
  'editor.inactiveSelectionBackground': `${black.tint[90]}40`,
  'editor.selectionHighlightBackground': primary.shade[70],
  'editor.wordHighlightBackground': primary.shade[70],
  'editor.wordHighlightStrongBackground': primary.shade[30],
  'editor.wordHighlightTextBackground': primary.shade[70],
  'editor.findMatchBackground': `${primary.DEFAULT}BF`,
  'editor.findMatchHighlightBackground': `${primary.DEFAULT}80`,
  'editor.findRangeHighlightBackground': black.tint[30],
  'search.resultsInfoForeground': info.DEFAULT,
  'searchEditor.findMatchBackground': `${primary.DEFAULT}BF`,
  'searchEditor.textInputBorder': primary.shade[30],
  'editor.hoverHighlightBackground': primary.shade[30],
  'editor.lineHighlightBackground': black.tint[30],
  'editorUnicodeHighlight.border': TESTING,
  'editorUnicodeHighlight.background': TESTING,
  'editorLink.activeForeground': white.shade[10],
  'editor.rangeHighlightBackground': black.tint[30],
  'editor.symbolHighlightBackground': primary.shade[70],
  'editorIndentGuide.activeBackground': primary.DEFAULT,
  'editorInlayHint.background': TESTING,
  'editorInlayHint.foreground': TESTING,
  'editorInlayHint.typeForeground': TESTING,
  'editorInlayHint.typeBackground': TESTING,
  'editorInlayHint.parameterForeground': TESTING,
  'editorInlayHint.parameterBackground': TESTING,
  'editorRuler.foreground': black.tint[30],
  'editor.linkedEditingBackground': TESTING,
  'editor.foldBackground': black.tint[30],
  'editorError.foreground': danger.DEFAULT,
  'editorWarning.foreground': warning.DEFAULT,
  'editorInfo.foreground': info.DEFAULT,
  'problemsErrorIcon.foreground': TESTING,
  'problemsWarningIcon.foreground': TESTING,
  'problemsInfoIcon.foreground': TESTING,
  'editorUnnecessaryCode.border': TESTING,
  'editorUnnecessaryCode.opacity': TESTING,
};
