import { colors } from '@synxty/design-tokens';

const editorKeys = [
  "editor.background",
  "editor.foreground",
  "editorLineNumber.foreground",
  "editorLineNumber.activeForeground",
  "editorLineNumber.dimmedForeground",
  "editorCursor.background",
  "editorCursor.foreground",
  "editor.selectionBackground",
  "editor.selectionForeground",
  "editor.inactiveSelectionBackground",
  "editor.selectionHighlightBackground",
  "editor.selectionHighlightBorder",
  "editor.wordHighlightBackground",
  "editor.wordHighlightBorder",
  "editor.wordHighlightStrongBackground",
  "editor.wordHighlightStrongBorder",
  "editor.wordHighlightTextBackground",
  "editor.wordHighlightTextBorder",
  "editor.findMatchBackground",
  "editor.findMatchHighlightBackground",
  "editor.findRangeHighlightBackground",
  "editor.findMatchBorder",
  "editor.findMatchHighlightBorder",
  "editor.findRangeHighlightBorder",
  "search.resultsInfoForeground",
  "searchEditor.findMatchBackground",
  "searchEditor.findMatchBorder",
  "searchEditor.textInputBorder",
  "editor.hoverHighlightBackground",
  "editor.lineHighlightBackground",
  "editor.lineHighlightBorder",
  "editorUnicodeHighlight.border",
  "editorUnicodeHighlight.background",
  "editorLink.activeForeground",
  "editor.rangeHighlightBackground",
  "editor.rangeHighlightBorder",
  "editor.symbolHighlightBackground",
  "editor.symbolHighlightBorder",
  "editorWhitespace.foreground",
  "editorIndentGuide.background",
  "editorIndentGuide.activeBackground",
  "editorInlayHint.background",
  "editorInlayHint.foreground",
  "editorInlayHint.typeForeground",
  "editorInlayHint.typeBackground",
  "editorInlayHint.parameterForeground",
  "editorInlayHint.parameterBackground",
  "editorRuler.foreground",
  "editor.linkedEditingBackground"
] as const;

type EditorColors = Partial<{ [K in typeof editorKeys[number]]: string }>; ;

export const editorColors: EditorColors = {
  "editor.background": colors.black.tint?.[10],
  "editor.foreground": colors.white.shade?.[10],
  "editorLineNumber.foreground": colors.bittersweet.tint[10],
  "editorLineNumber.activeForeground": colors.bittersweet.DEFAULT,
}
