name: CI

on:
  push:
    branches: ['main']
  pull_request:
    types: [opened, synchronize]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
  FIGMA_FILE_ID: ${{ secrets.FIGMA_FILE_ID }}
  WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          token: WORKFLOW_TOKEN

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setting up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@synxty'
          cache: 'pnpm'

      - name: Installing dependencies
        run: pnpm install

      - name: Formatting
        run: pnpm format

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.16.0

      - name: Building
        run: pnpm build

      - name: Testing
        run: pnpm test
