name: CI

on:
  push:
    branches: ['main']
  pull_request:
    types: [opened, synchronize]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
  FIGMA_FILE_ID: ${{ secrets.FIGMA_FILE_ID }}

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup
        uses: ./.github/workflows/setup

      - name: Formatting
        run: pnpm format

      - name: Check for Changes
        id: check_changes
        run: git diff --quiet || echo "Changes detected"

      - name: Commit Changes
        if: steps.check_changes.outputs.result == 'Changes detected'
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Commit message"
          git push

  test:
    needs: format
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        uses: ./.github/workflows/setup

      - name: Testing
        run: pnpm test

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        uses: ./.github/workflows/setup

      - name: Building
        run: pnpm build
