name: Release
on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-{{ github.ref }}

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
  FIGMA_FILE_ID: ${{ secrets.FIGMA_FILE_ID }}
  VSCE_PAT: ${{ secrets.VSCE_PAT }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@synxty'
          cache: "pnpm"

      - run: pnpm install

      - name: Building packages...
        run: pnpm build
        
      - name: Create Release Pull Request or Publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm ci:version
          publish: pnpm release
          commit: 'Release: Version Packages'
          title: 'Release: Version Packages'